name: thingsboard_client
description: Dart implementation of ThingsBoard API client. Provides model objects and services to communicate with ThingsBoard platform using RESTful APIs and WebSocket protocol.
version: 1.0.6
homepage: https://thingsboard.io
repository: https://github.com/thingsboard/dart_thingsboard_client.git
issue_tracker: https://github.com/thingsboard/dart_thingsboard_client/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  dio: ^4.0.6
  jwt_decoder: ^2.0.1
  web_socket_channel: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  pedantic: ^1.11.1
  test: ^1.21.4
