name: thingsboard_client
description: Dart implementation of ThingsBoard API client. Provides model objects and services to communicate with ThingsBoard platform using RESTful APIs and WebSocket protocol.
version: 1.0.2
homepage: https://thingsboard.io
repository: https://github.com/thingsboard/dart_thingsboard_client.git
issue_tracker: https://github.com/thingsboard/dart_thingsboard_client/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  jwt_decoder: ^2.0.1
  web_socket_channel: ^2.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
