name: thingsboard_client
description: Dart implementation of ThingsBoard API client. Provides model objects and services to communicate with ThingsBoard platform using RESTful APIs and WebSocket protocol.
version: 1.3.1
homepage: https://thingsboard.io
repository: https://github.com/thingsboard/dart_thingsboard_client.git
issue_tracker: https://github.com/thingsboard/dart_thingsboard_client/issues

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  dio: ^5.3.4
  jwt_decoder: ^2.0.1
  web_socket_channel: ^2.4.0
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  lints: ^3.0.0
  pedantic: ^1.11.1
  test: ^1.24.9
